INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO:daphne.server:Listening on TCP address 127.0.0.1:8000
INFO:root:Got data
INFO:django.channels.server:[mHTTP GET /api/admin/users/ 200 [0.04, 127.0.0.1:56645][0m
INFO:root:m@gmail.com already exist
WARNING:django.request:Bad Request: /api/register/
WARNING:django.channels.server:[31;1mHTTP POST /api/register/ 400 [0.21, 127.0.0.1:56646][0m
INFO:root:m@gmail.com already exist
WARNING:django.request:Bad Request: /api/register/
WARNING:django.channels.server:[31;1mHTTP POST /api/register/ 400 [0.20, 127.0.0.1:56646][0m
INFO:root:mmm@gmail.com already exist
WARNING:django.request:Bad Request: /api/register/
WARNING:django.channels.server:[31;1mHTTP POST /api/register/ 400 [0.20, 127.0.0.1:56646][0m
INFO:django.utils.autoreload:/Users/malikshahid/PycharmProjects/python-trade-line/trade/tradeline/settings.py changed, reloading.
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO:daphne.server:Listening on TCP address 127.0.0.1:8000
INFO:root:mmm1@gmail.com already exist
WARNING:django.request:Bad Request: /api/register/
WARNING:django.channels.server:[31;1mHTTP POST /api/register/ 400 [0.20, 127.0.0.1:56648][0m
INFO:django.utils.autoreload:/Users/malikshahid/PycharmProjects/python-trade-line/trade/tradeline/settings.py changed, reloading.
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO:daphne.server:Listening on TCP address 127.0.0.1:8000
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO:daphne.server:Listening on TCP address 127.0.0.1:8000
INFO:root:mmm1@gmail.com already exist
WARNING:django.request:Bad Request: /api/register/
WARNING:django.channels.server:[31;1mHTTP POST /api/register/ 400 [0.20, 127.0.0.1:56652][0m
INFO:root:User saved successfully
INFO:root:OTP sent successfully
INFO:django.channels.server:[mHTTP POST /api/register/ 200 [3.58, 127.0.0.1:56652][0m
INFO:root:Got data
INFO:django.channels.server:[mHTTP GET /api/admin/users/ 200 [0.04, 127.0.0.1:56654][0m
INFO:django.channels.server:WebSocket HANDSHAKING /ws/chat/mmm21@gmail.com/ [127.0.0.1:56655]
ERROR:daphne.server:Exception inside application: No route found for path 'ws/chat/mmm21@gmail.com/'.
Traceback (most recent call last):
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/routing.py", line 168, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'ws/chat/mmm21@gmail.com/'.
INFO:django.channels.server:WebSocket DISCONNECT /ws/chat/mmm21@gmail.com/ [127.0.0.1:56655]
INFO:django.utils.autoreload:/Users/malikshahid/PycharmProjects/python-trade-line/trade/chatting/consumers.py changed, reloading.
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO:daphne.server:Listening on TCP address 127.0.0.1:8000
INFO:django.channels.server:WebSocket HANDSHAKING /ws/chat/1/ [127.0.0.1:56664]
INFO:django.channels.server:WebSocket CONNECT /ws/chat/1/ [127.0.0.1:56664]
INFO:django.utils.autoreload:/Users/malikshahid/PycharmProjects/python-trade-line/trade/chatting/consumers.py changed, reloading.
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO:daphne.server:Listening on TCP address 127.0.0.1:8000
INFO:django.channels.server:WebSocket HANDSHAKING /ws/chat/c58800c7cc70e10576c9a4208f841980e88bbd36/ [127.0.0.1:56668]
ERROR:daphne.server:Exception inside application: User matching query does not exist.
Traceback (most recent call last):
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/trade/chatting/consumers.py", line 20, in websocket_connect
    me = await sync_to_async(User.objects.get)(auth_token=username)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
trade.models.User.DoesNotExist: User matching query does not exist.
INFO:django.channels.server:WebSocket DISCONNECT /ws/chat/c58800c7cc70e10576c9a4208f841980e88bbd36/ [127.0.0.1:56668]
INFO:django.channels.server:WebSocket HANDSHAKING /ws/chat/c58800c7cc70e10576c9a4208f841980e88bbd36/ [127.0.0.1:56669]
ERROR:daphne.server:Exception inside application: User matching query does not exist.
Traceback (most recent call last):
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/trade/chatting/consumers.py", line 20, in websocket_connect
    me = await sync_to_async(User.objects.get)(auth_token=username)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
trade.models.User.DoesNotExist: User matching query does not exist.
INFO:django.channels.server:WebSocket DISCONNECT /ws/chat/c58800c7cc70e10576c9a4208f841980e88bbd36/ [127.0.0.1:56669]
INFO:django.channels.server:WebSocket HANDSHAKING /ws/chat/c58800c7cc70e10576c9a4208f841980e88bbd36/ [127.0.0.1:56670]
ERROR:daphne.server:Exception inside application: User matching query does not exist.
Traceback (most recent call last):
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/trade/chatting/consumers.py", line 20, in websocket_connect
    me = await sync_to_async(User.objects.get)(auth_token=username)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/malikshahid/PycharmProjects/python-trade-line/venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
trade.models.User.DoesNotExist: User matching query does not exist.
INFO:django.channels.server:WebSocket DISCONNECT /ws/chat/c58800c7cc70e10576c9a4208f841980e88bbd36/ [127.0.0.1:56670]
INFO:django.utils.autoreload:/Users/malikshahid/PycharmProjects/python-trade-line/trade/chatting/consumers.py changed, reloading.
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO:daphne.server:Listening on TCP address 127.0.0.1:8000
INFO:django.channels.server:WebSocket HANDSHAKING /ws/chat/1/ [127.0.0.1:56672]
INFO:django.channels.server:WebSocket CONNECT /ws/chat/1/ [127.0.0.1:56672]
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO:daphne.server:Listening on TCP address 127.0.0.1:8000
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=192.168.18.112
INFO:daphne.server:Listening on TCP address 192.168.18.112:8000
WARNING:django.request:Not Found: /
WARNING:django.channels.server:[33mHTTP GET / 404 [0.04, 192.168.18.112:49578][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/user_detail/ 200 [0.02, 192.168.18.80:39294][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/pay/ 200 [0.02, 192.168.18.80:39296][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/order_card/ 200 [0.02, 192.168.18.80:39298][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/user_detail/ 200 [0.02, 192.168.18.80:39300][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/pay/ 200 [0.02, 192.168.18.80:39302][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/order_card/ 200 [0.02, 192.168.18.80:39304][0m
INFO:root:Invalid Credentials
WARNING:django.request:Bad Request: /api/login/
WARNING:django.channels.server:[31;1mHTTP POST /api/login/ 400 [0.19, 192.168.18.80:39450][0m
INFO:root:User Does Not Exist
WARNING:django.request:Bad Request: /api/user_detail/
WARNING:django.channels.server:[31;1mHTTP GET /api/user_detail/ 400 [0.01, 192.168.18.105:44556][0m
INFO:root:946065e317d37e141eeac12bc53d3a0363d77d2e User Does not exist
WARNING:django.request:Bad Request: /api/order_card/
INFO:django.channels.server:[mHTTP GET /api/pay/ 200 [0.02, 192.168.18.105:44560][0m
WARNING:django.channels.server:[31;1mHTTP GET /api/order_card/ 400 [0.02, 192.168.18.105:44558][0m
WARNING:django.request:Not Found: /media/IMG-0038.apng
WARNING:django.channels.server:[33mHTTP GET /media/IMG-0038.apng 404 [0.01, 192.168.18.105:44562][0m
WARNING:django.request:Not Found: /media/IMG-0038.apng
WARNING:django.channels.server:[33mHTTP GET /media/IMG-0038.apng 404 [0.01, 192.168.18.105:44562][0m
INFO:root:User Does Not Exist
INFO:root:946065e317d37e141eeac12bc53d3a0363d77d2e User Does not exist
WARNING:django.request:Not Found: /media/IMG-0038.apng
WARNING:django.request:Bad Request: /api/user_detail/
WARNING:django.request:Bad Request: /api/order_card/
INFO:root:User Does Not Exist
INFO:root:946065e317d37e141eeac12bc53d3a0363d77d2e User Does not exist
WARNING:django.request:Bad Request: /api/user_detail/
WARNING:django.request:Bad Request: /api/order_card/
INFO:django.channels.server:[mHTTP GET /api/pay/ 200 [0.03, 192.168.18.105:44602][0m
WARNING:django.channels.server:[31;1mHTTP GET /api/user_detail/ 400 [0.03, 192.168.18.105:44600][0m
WARNING:django.channels.server:[31;1mHTTP GET /api/order_card/ 400 [0.03, 192.168.18.105:44598][0m
INFO:django.utils.autoreload:/Users/malikshahid/PycharmProjects/python-trade-line/trade/tradeline/settings.py changed, reloading.
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=192.168.18.112
INFO:daphne.server:Listening on TCP address 192.168.18.112:8000
INFO:root:Invalid Credentials
WARNING:django.request:Bad Request: /api/login/
WARNING:django.channels.server:[31;1mHTTP POST /api/login/ 400 [0.18, 192.168.18.80:40236][0m
INFO:root:Invalid Credentials
WARNING:django.request:Bad Request: /api/login/
WARNING:django.channels.server:[31;1mHTTP POST /api/login/ 400 [0.17, 192.168.18.80:40236][0m
INFO:root:User saved successfully
INFO:root:OTP sent successfully
INFO:django.channels.server:[mHTTP POST /api/register/ 200 [10.20, 192.168.18.105:44646][0m
WARNING:django.request:Not Found: /api/admin/users
WARNING:django.channels.server:[33mHTTP GET /api/admin/users 404 [0.02, 192.168.18.25:61807][0m
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.channels.server:[33mHTTP GET /favicon.ico 404 [0.01, 192.168.18.25:61807][0m
INFO:root:Got data
INFO:django.channels.server:[mHTTP GET /api/admin/users/ 200 [0.05, 192.168.18.25:61807][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/css/bootstrap.min.css 200 [0.02, 192.168.18.25:61807][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/css/bootstrap-tweaks.css 200 [0.02, 192.168.18.25:64939][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/css/prettify.css 200 [0.01, 192.168.18.25:59479][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/css/default.css 200 [0.01, 192.168.18.25:60997][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/js/jquery-3.5.1.min.js 200 [0.01, 192.168.18.25:50541][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/js/ajax-form.js 200 [0.00, 192.168.18.25:53225][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/js/csrf.js 200 [0.01, 192.168.18.25:64939][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/js/bootstrap.min.js 200 [0.01, 192.168.18.25:59479][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/js/prettify-min.js 200 [0.02, 192.168.18.25:60997][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/js/default.js 200 [0.01, 192.168.18.25:53225][0m
INFO:django.channels.server:[mHTTP GET /static/rest_framework/img/grid.png 200 [0.01, 192.168.18.25:60997][0m
INFO:root:Invalid Credentials
WARNING:django.request:Bad Request: /api/login/
WARNING:django.channels.server:[31;1mHTTP POST /api/login/ 400 [0.19, 192.168.18.80:40236][0m
INFO:root:adilijaz.09@gmail.com Verified through OTP
INFO:django.channels.server:[mHTTP POST /api/otp/ 200 [0.01, 192.168.18.105:44646][0m
INFO:root:Invalid Credentials
WARNING:django.request:Bad Request: /api/login/
WARNING:django.channels.server:[31;1mHTTP POST /api/login/ 400 [0.20, 192.168.18.80:40236][0m
INFO:root:User saved successfully
INFO:root:OTP sent successfully
INFO:django.channels.server:[mHTTP POST /api/register/ 200 [5.62, 192.168.18.80:40236][0m
INFO:root:adilijaz.09@gmail.com Data Saved
INFO:django.channels.server:[mHTTP POST /api/registration/ 200 [3.39, 192.168.18.105:44646][0m
INFO:root:adilijaz.09@gmail.com is logged in
INFO:django.channels.server:[mHTTP POST /api/login/ 200 [0.20, 192.168.18.105:44646][0m
INFO:root:adilijaz.09@gmail.com got data
INFO:django.channels.server:[mHTTP GET /api/user_detail/ 200 [0.02, 192.168.18.105:44646][0m
INFO:django.channels.server:[mHTTP GET /api/pay/ 200 [0.03, 192.168.18.105:44742][0m
INFO:django.channels.server:[mHTTP GET /api/order_card/ 200 [0.03, 192.168.18.105:44744][0m
WARNING:django.request:Not Found: /media/IMG-0041.apng
WARNING:django.channels.server:[33mHTTP GET /media/IMG-0041.apng 404 [0.01, 192.168.18.105:44748][0m
WARNING:django.request:Not Found: /media/IMG-0041.apng
WARNING:django.channels.server:[33mHTTP GET /media/IMG-0041.apng 404 [0.01, 192.168.18.105:44748][0m
WARNING:django.request:Not Found: /media/IMG-0041.apng
WARNING:django.channels.server:[33mHTTP GET /media/IMG-0041.apng 404 [0.01, 192.168.18.105:44748][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/otp/ 200 [0.00, 192.168.18.80:40236][0m
INFO:root:aizaz9790@gmail.com Verified through OTP
INFO:django.channels.server:[mHTTP POST /api/otp/ 200 [0.02, 192.168.18.80:40236][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/registration/ 200 [0.02, 192.168.18.80:40236][0m
INFO:root:aizaz9790@gmail.com Data Saved
INFO:django.channels.server:[mHTTP POST /api/registration/ 200 [0.48, 192.168.18.80:40236][0m
WARNING:django.request:Not Found: /media/IMG-0041.apng
WARNING:django.channels.server:[33mHTTP GET /media/IMG-0041.apng 404 [0.01, 192.168.18.105:44832][0m
INFO:root:aizaz9790@gmail.com is logged in
INFO:django.channels.server:[mHTTP POST /api/login/ 200 [0.20, 192.168.18.80:40236][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/user_detail/ 200 [0.00, 192.168.18.80:40236][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/pay/ 200 [0.01, 192.168.18.80:41614][0m
INFO:django.channels.server:[mHTTP OPTIONS /api/order_card/ 200 [0.01, 192.168.18.80:40236][0m
INFO:root:aizaz9790@gmail.com got data
INFO:django.channels.server:[mHTTP GET /api/user_detail/ 200 [0.02, 192.168.18.80:41616][0m
INFO:django.channels.server:[mHTTP GET /api/pay/ 200 [0.02, 192.168.18.80:41614][0m
INFO:django.channels.server:[mHTTP GET /api/order_card/ 200 [0.02, 192.168.18.80:40236][0m
INFO:django.utils.autoreload:/Users/malikshahid/PycharmProjects/python-trade-line/trade/tradeline/urls.py changed, reloading.
INFO:daphne.server:HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO:daphne.server:Configuring endpoint tcp:port=8000:interface=192.168.18.112
INFO:daphne.server:Listening on TCP address 192.168.18.112:8000
INFO:root:adilijaz.09@gmail.com got data
INFO:root:adilijaz.09@gmail.com got data
WARNING:django.request:Not Found: /
WARNING:django.channels.server:[33mHTTP GET / 404 [0.06, 192.168.18.105:44858][0m
INFO:django.channels.server:[mHTTP GET /api/user_detail/ 200 [0.05, 192.168.18.105:44866][0m
INFO:django.channels.server:[mHTTP GET /api/user_detail/ 200 [0.05, 192.168.18.105:44862][0m
INFO:django.channels.server:[mHTTP GET /media/IMG-0041.apng 200 [0.05, 192.168.18.105:44868][0m
INFO:django.channels.server:[mHTTP GET /api/pay/ 200 [0.06, 192.168.18.105:44860][0m
INFO:django.channels.server:[mHTTP GET /api/order_card/ 200 [0.06, 192.168.18.105:44864][0m
INFO:django.channels.server:[mHTTP PUT /api/update/ 200 [0.29, 192.168.18.105:44864][0m
INFO:root:adilijaz.09@gmail.com got data
INFO:django.channels.server:[mHTTP GET /api/pay/ 200 [0.03, 192.168.18.105:44864][0m
INFO:django.channels.server:[mHTTP GET /api/user_detail/ 200 [0.03, 192.168.18.105:44866][0m
INFO:django.channels.server:[mHTTP GET /api/order_card/ 200 [0.03, 192.168.18.105:44860][0m
INFO:django.channels.server:[mHTTP GET /media/IMG-0036_pz7CCps.apng 200 [0.01, 192.168.18.105:44858][0m
